version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - cd fe
      - yarn install --lock-file

  build:
    commands:
      - cd fe
      - yarn build
