name: WaiterApp CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'

    - name: Install dependecies
      working-directory: WaiterApp/fe
      run: yarn install --frozen-lockfile 

    - name: Linting
      working-directory: WaiterApp/fe
      run: yarn ci:lint 

    - name: Typechecking
      working-directory: WaiterApp/fe
      run: yarn typecheck

    - name: Teste
      working-directory: WaiterApp/fe
      run: yarn test:ci
